# SPDX-FileCopyrightText: 2020-2025 Nicotine+ Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

name: Packaging
on: [push, pull_request]
permissions: {}

jobs:

  macos:
    runs-on: macos-15
    timeout-minutes: 45
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Create Python virtual environment
        run: |
          brew uninstall --ignore-dependencies python@3.14
          brew install --overwrite python@3.14
          python3.14 -m venv venv

      - name: Install build dependencies
        run: venv/bin/python3 build-aux/macos/dependencies.py

      - name: Freeze application
        run: venv/bin/python3 build-aux/macos/setup.py bdist_dmg

      - name: Archive installer artifacts
        uses: actions/upload-artifact@v7
        with:
          name: macos-arm64-installer
          path: build-aux/macos/build/*.dmg
